"""PES21 4cc fmdl -> PES2012 per-player custom body (drawlogic.dll format).

    python3 fmdl_to_pes12.py <body.fmdl> <texture.dds> <out_dir>

Writes <out_dir>/body.bin (vertices + indices) and <out_dir>/body.tex
(u32 'PGT1', w, h, mips, then BGRA8 mips largest first; decoded here by
PIL because uploading the DXT5 blocks through DXVK's d3d9 came out black).

Bones: the 19 main bones of the in-match body (dt09 #349 block 2,
rig/body349b2_bones.json, regenerated by pes12_rig.py from your game);
BLENDINDICES are that body's palette slots, and
drawlogic uploads one matrix per slot at c20 + 3*slot itself.
Vertex format = the LOD0 kit's packet-5 declaration (dt0c #3, 755 verts/80 B,
grabbed 24-09): POSITION f3 | BLENDWEIGHT f3 | BLENDINDICES ubyte4 | NORMAL f3
| BINORMAL f3 | TANGENT f3 | TEXCOORD0 f2 | TEXCOORD1 f2 = 80 bytes.

Both games agree on basis: Y up, +Z forward, +X = the character's left
(PES12 thigh_l x=+0.09 like Fox sk_thigh_l; feet reach +z in both).

Pose: the fmdl is authored in Fox's RENDER bind (arms ~45 deg down); PES12's
bind is a T-pose. Each influence is re-posed rigidly about its bone:
    v12 = sum_b w_b * (P12(b) + W(b) (v - A(b)))
with A = Fox render-bind joint, W = retarget.PES_ALIGN (render -> anim pose,
identity on the trunk) and P12 = the PES12 joint the Fox bone maps to. The
per-bone translation also absorbs the proportion difference between the two
skeletons (PES12 hands at +-0.704 m, Fox anim hands at +-0.770 m).
"""
import json
import math
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VENDOR = os.environ.get('PES12_VENDOR', os.path.join(HERE, 'vendor'))
sys.path.insert(0, VENDOR)
import retarget  # noqa: E402
import FmdlFile  # noqa: E402

BONES_JSON = os.environ.get('PES12_BODY_BONES',
                            os.path.join(os.environ.get('PES12_RIG', os.path.join(HERE, 'rig')),
                                         'body349b2_bones.json'))

# Fox main bone -> PES12 dt09#349 block-2 bone index (by bind position and
# parent chain, rig/body349b2_bones.json).
FOX_TO_PES12 = {
    'motion': 0, 'dsk_hip': 0,
    'sk_thigh_l': 1, 'sk_thigh_r': 2,
    'sk_belly': 3,
    'sk_leg_l': 4, 'sk_leg_r': 5,
    'sk_chest': 6,
    'sk_foot_l': 7, 'sk_foot_r': 8,
    'sk_neck': 9,
    'sk_shoulder_l': 10, 'sk_shoulder_r': 11,
    'sk_upperarm_l': 12, 'sk_upperarm_r': 13,
    'sk_head': 14,
    'sk_forearm_l': 15, 'sk_forearm_r': 16,
    'sk_hand_l': 17, 'sk_hand_r': 18,
}
PES_OF_GF = {gf: pes for gf, pes, _ in retarget.GF_NODES}
MAX_INFLUENCES = 4          # UBYTE4 BLENDINDICES
MIN_WEIGHT = 1.5 / 255      # one 8-bit step (1/255) is 4cc authoring noise: Caulifla knee verts carry sk_upperarm at exactly 1/255
VERTEX_STRIDE = 80
FACE_REST_OFF = 28          # vertex bytes after POSITION f3 | BLENDWEIGHT f3 | BLENDINDICES ubyte4
BODY_MAGIC = 0x31424750     # 'PGB1'
U16_MAX_VERTS = 65535
# PES2012's kit rig bends the four fingers of each hand as one bone (57-bone
# table bones 52/53, children of the hands at the wrist, 27-09); drawlogic
# uploads them as our slots 19/20 (dllprobe/kitmap.h). Thumbs have no bone
# there and stay on the hand.
FINGER_SLOT = {'sk_hand_l': 19, 'sk_hand_r': 20}
FINGER_BONE = re.compile(r'skh_(index|middle|ring|pinky)_')


def slot_key(name, fox):
    """Influence key: the main bone, or (hand, finger group) for finger bones."""
    return (fox, True) if FINGER_BONE.match(name) and fox in FINGER_SLOT else (fox, False)


def key_slot(key, slot_of):
    fox, finger = key
    return FINGER_SLOT[fox] if finger else slot_of[FOX_TO_PES12[fox]]


def main_bone(name, fmdl_bind):
    """fmdl bone (helpers included) -> animated Fox bone it rigidly follows."""
    if name in FOX_TO_PES12:
        return name
    gf = retarget.resolve_bone(name, fmdl_bind)
    pes = PES_OF_GF.get(gf)
    if pes is None:
        raise KeyError('unmapped bone %s' % name)
    if pes.startswith('skh_'):  # fingers ride the hand in a 19-bone body
        pes = 'sk_hand_l' if pes.endswith('_l') else 'sk_hand_r'
    return pes


TEX_MAGIC = 0x31544750      # 'PGT1'


def write_tex(src, dst):
    from PIL import Image
    im = Image.open(src).convert('RGBA')
    mips = []
    w, h = im.size
    while True:
        r, g, b, a = im.resize((w, h), Image.LANCZOS).split() if (w, h) != im.size else im.split()
        mips.append(Image.merge('RGBA', (b, g, r, a)).tobytes())
        if w == 1 and h == 1:
            break
        w, h = max(1, w // 2), max(1, h // 2)
    with open(dst, 'wb') as o:
        o.write(struct.pack('<4I', TEX_MAGIC, im.size[0], im.size[1], len(mips)))
        for m in mips:
            o.write(m)


def convert(fmdl_path, dds_path, out_dir):
    table = json.load(open(BONES_JSON))
    slot_of = {b['bone']: b['slot'] for b in table['bones']}
    p12 = {b['bone']: b['pos'] for b in table['bones']}

    f = FmdlFile.FmdlFile()
    f.readFile(fmdl_path)
    fmdl_bind = {}
    for b in f.bones:
        # bone.globalPosition is the render-bind joint (Fox coords)
        gp = b.globalPosition
        fmdl_bind[b.name] = (gp.x, gp.y, gp.z)

    # the drawable mesh: skip "antiblur" duplicates and degenerate stubs
    meshes = [m for m in f.meshes if 'antiblur' not in m.materialInstance.name
              and len(m.faces) > 1]
    verts, idx = [], []
    for m in meshes:
        base = len(verts)
        index_of = {id(v): k for k, v in enumerate(m.vertices)}
        for v in m.vertices:
            infl = {}
            for bone, w in v.boneMapping.items():
                key = slot_key(bone.name, main_bone(bone.name, fmdl_bind))
                infl[key] = infl.get(key, 0.0) + w
            # 4cc exports list bones at weight 0.0 (Caulifla's knee verts carry
            # sk_upperarm_l at 0.0); kept, they take an index slot and the
            # implicit remainder lands on them - a fin from knee to shoulder.
            infl = {b: w for b, w in infl.items() if w >= MIN_WEIGHT}
            top = sorted(infl.items(), key=lambda kv: -kv[1])[:MAX_INFLUENCES]
            tw = sum(w for _, w in top) or 1.0
            top = [(b, w / tw) for b, w in top]
            p = (v.position.x, v.position.y, v.position.z)
            n = (v.normal.x, v.normal.y, v.normal.z)
            tg = (v.tangent.x, v.tangent.y, v.tangent.z) if v.tangent else (1.0, 0.0, 0.0)
            pos = [0.0, 0.0, 0.0]
            nrm = [0.0, 0.0, 0.0]
            tan = [0.0, 0.0, 0.0]
            for (fox, _), w in top:
                a = retarget.PES_RENDER_BIND[fox][0]
                q = retarget.PES_ALIGN.get(fox, (0.0, 0.0, 0.0, 1.0))
                r = retarget._q_rot(q, tuple(pi - ai for pi, ai in zip(p, a)))
                t = p12[FOX_TO_PES12[fox]]
                rn = retarget._q_rot(q, n)
                rt = retarget._q_rot(q, tg)
                for k in range(3):
                    pos[k] += w * (t[k] + r[k])
                    nrm[k] += w * rn[k]
                    tan[k] += w * rt[k]
            ln = math.sqrt(sum(c * c for c in nrm)) or 1.0
            nrm = [c / ln for c in nrm]
            lt = math.sqrt(sum(c * c for c in tan)) or 1.0
            tan = [c / lt for c in tan]
            bin_ = [nrm[1] * tan[2] - nrm[2] * tan[1], nrm[2] * tan[0] - nrm[0] * tan[2],
                    nrm[0] * tan[1] - nrm[1] * tan[0]]
            # PES12's convention (grabbed kit packet 5, 24-09): n bones carry
            # n-1 explicit weights; the remainder belongs to the bone after the
            # last explicit one. Padding every remaining index with the last bone
            # makes the remainder land on it whichever slot the shader reads.
            slots = [key_slot(b, slot_of) for b, _ in top]
            ws = [w for _, w in top][:-1]
            while len(slots) < MAX_INFLUENCES:
                slots.append(slots[-1])
            while len(ws) < MAX_INFLUENCES:
                ws.append(0.0)
            uv = v.uv[0] if v.uv else None
            u, vv = (uv.u, uv.v) if uv is not None else (0.0, 0.0)
            verts.append(struct.pack('<3f3f4B3f3f3f2f2f', *pos, *ws[:3], *slots, *nrm, *bin_, *tan, u, vv, u, vv))
        for face in m.faces:
            idx.extend(base + index_of[id(face.vertices[k])] for k in (0, 1, 2))
    if len(verts) > U16_MAX_VERTS:
        raise ValueError('%d vertices exceed 16-bit indices' % len(verts))

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'body.bin'), 'wb') as o:
        o.write(struct.pack('<4I', BODY_MAGIC, len(verts), len(idx), VERTEX_STRIDE))
        o.write(b''.join(verts))
        o.write(struct.pack('<%dH' % len(idx), *idx))
    write_tex(dds_path, os.path.join(out_dir, 'body.tex'))
    ys = [struct.unpack_from('<3f', v)[1] for v in verts]
    print('wrote %d verts, %d tris, y %.2f..%.2f' % (len(verts), len(idx) // 3, min(ys), max(ys)))


if __name__ == '__main__':
    convert(*sys.argv[1:4])
