#!/bin/sh
# custom_ps.hlsl -> custom_ps.h (ps_3_0 bytecode arrays for
# drawlogic.cpp). Needs vkd3d-compiler (vkd3d); rerun after editing the HLSL.
set -e
cd "$(dirname "$0")"
tmp=$(mktemp -d)
out=custom_ps.h
echo "// generated by tools/build_shaders.sh from custom_ps.hlsl - do not edit" > $out
for entry in shadeless toon; do
    vkd3d-compiler -x hlsl -b d3dbc -p ps_3_0 -e $entry -o "$tmp/$entry.bin" custom_ps.hlsl
    python3 - "$tmp/$entry.bin" $entry >> $out <<'PY'
import sys
b = open(sys.argv[1], 'rb').read()
w = [int.from_bytes(b[k:k + 4], 'little') for k in range(0, len(b), 4)]
print('static const DWORD PS_%s[] = {' % sys.argv[2].upper())
for k in range(0, len(w), 8):
    print('    ' + ', '.join('0x%08x' % v for v in w[k:k + 8]) + ',')
print('};')
PY
done
rm -r "$tmp"
echo "wrote $out"
