// generated by tools/pes12_rig.py from dt09 #349 blocks 1 (officials) and 2 (body)
// our slot s (block 2 palette order) -> the official draw's palette slot
static const int OFFICIAL_SLOT[19] = {3, 2, 12, 1, 0, 17, 18, 4, 10, 9, 11, 5, 6, 7, 8, 13, 16, 15, 14};
// the officials' vertex buffer: every packet's vertices, 16-aligned
static const UINT OFFICIAL_VB_BYTES = 291392;
