// generated by tools/pes12_rig.py from dt09 #349 blocks 1 (officials) and 2 (body)
// our slot s (block 2 palette order) -> the official draw's palette slot
static const int OFFICIAL_SLOT[19] = {3, 2, 12, 1, 0, 17, 18, 4, 10, 9, 11, 5, 6, 7, 8, 13, 16, 15, 14};
// the officials' vertex buffer size band: lo <= size < hi
static const UINT OFFICIAL_VB_LO = 291348, OFFICIAL_VB_HI = 291732;
// rigid face: the head bone (our slot), its bind position (m), the face palette size
static const UINT HEAD_SLOT = 18;
static const float HEAD_BIND[3] = {0.00000f, 1.64952f, -0.00451f};
static const UINT FACE_SLOTS = 27;
// close-up model (block 0): our slot -> (palette group, slot); groups start at
// these VB bytes (the game draws a group's packets in VB order)
static const UINT CLOSE_VB_LO = 593236, CLOSE_VB_HI = 593636;
static const UINT CLOSE_GROUPS = 2;
static const UINT CLOSE_GROUP_START[2] = {0, 273356};
static const int CLOSE_SRC_GROUP[19] = {0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1};
static const int CLOSE_SRC_SLOT[19] = {3, 5, 20, 0, 2, 7, 10, 9, 16, 19, 0, 13, 19, 18, 5, 21, 3, 29, 12};
